// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajcmxmboshohzczvdixy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqY214bWJvc2hvaHpjenZkaXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODkyMTIsImV4cCI6MjA2MTA2NTIxMn0.gpvfN1_u7mUDcfd2HOHxcUckmhW0ar4qZ7BfrRqUQBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);